issuer: https://token.actions.githubusercontent.com
subject: repo:liatri0@295244123/avr_auto-version-and-release@1393754126:ref:refs/heads/main
permissions:
  contents: write  # create tags + releases
